get status of docker images

diff --git a/.github/workflows/build-images.yml b/.github/workflows/build-images.yml
--- a/.github/workflows/build-images.yml
+++ b/.github/workflows/build-images.yml
@@ -11,6 +11,7 @@ env:
   REPOSITORY: molten-verve-216720/demo-repository
   DOCKER_COMPOSE_PATH: "config/docker-compose.yml"  # path to docker compose in repository
   SLEEP_DURATION: 60                                # Duration to sleep before setup complete
+  CONTAINERS_EXPECTED_TO_BE_RUNNING: "etcd0 etcd1 etcd2 client"   # containers we expect to be running by setup_complete
 
 jobs:
   build-and-push:
@@ -48,6 +49,12 @@ jobs:
           ${{ env.REGISTRY }}/${{ env.REPOSITORY}}/etcd-client:latest,
           ${{ env.REGISTRY }}/${{ env.REPOSITORY}}/etcd-client:${{ github.sha }}
 
+    - name: Install Docker using Docker's official script
+      run: |
+            curl -fsSL https://get.docker.com -o get-docker.sh 
+            sudo sh get-docker.sh
+      continue-on-error: false
+
     - name: Install Docker Compose
       run: |
           sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
@@ -57,6 +64,23 @@ jobs:
 
     - name: Start application-specific services using Docker Compose
       run: docker-compose -f $DOCKER_COMPOSE_PATH up -d
+      continue-on-error: false
+
+    - name: Validate our expected containers are running
+      run: |
+          EXPECTED_CONTAINERS=$CONTAINERS_EXPECTED_TO_BE_RUNNING
+
+          for container in "${EXPECTED_CONTAINERS[@]}"; do
+            CONTAINERS_RUNNING=$(docker ps --filter "name=$container" --filter "status=running" --format "{{.Names}}")
+
+            if [[ ! "$CONTAINER_RUNNING" =~ "$container" ]]; then
+              echo "Error: The container '$container' is not running!"
+              exit 1
+            fi
+            echo "The container '$container' is running."
+          done
+
+          echo "All expected containers are running"
       continue-on-error: false
 
     - name: Sleep until setup_complete
@@ -73,4 +97,4 @@ jobs:
             i=$((i + 1))
 
           done
-      continue-on-error: false
+      continue-on-error: false 
